# Generated by Django 4.0.1 on 2022-01-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_staff',
            name='cat_filter',
            field=models.CharField(choices=[('*', '*'), ('Restaurant', 'Restaurant'), ('Spa - Beauty & Health', 'Spa - Beauty & Health'), ('Conference Room', 'Conference Room'), ('Swimming Pool', 'Swimming Pool'), ('Fitness', 'Fitness')], default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category_gallery',
            name='cat_filter',
            field=models.CharField(choices=[('*', '*'), ('.filter-restaurant', '.filter-restaurant'), ('.filter-room', '.filter-room'), ('.filter-fitess', '.filter-fitess'), ('.filter-spa', '.filter-spa'), ('.filter-swimming', '.filter-swimming'), ('.filter-other', '.filter-other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cat_filter',
            field=models.CharField(choices=[('*', '*'), ('filter-restaurant', 'filter-restaurant'), ('filter-room', 'filter-room'), ('filter-fitess', 'filter-fitess'), ('filter-spa', 'filter-spa'), ('filter-swimming', 'filter-swimming'), ('filter-other', 'filter-other')], max_length=255),
        ),
    ]
